schema_version = "1.0.0"

id = "realtime_fcurves"
version = "1.0.0"
name = "Realtime F-Curves"
tagline = "F-Curves that update in realtime with transformed bones"
maintainer = "MrKoix"

tags = ["Animation"]

type = "add-on"

blender_version_min = "4.0.0"  # Minimum Blender version supported

license = ["GPL-3.0"]
